In [1]:
%pip install gdown
import gdown

Collecting gdown
  Using cached gdown-5.2.0-py3-none-any.whl.metadata (5.8 kB)
Collecting beautifulsoup4 (from gdown)
  Downloading beautifulsoup4-4.14.2-py3-none-any.whl.metadata (3.8 kB)
Collecting filelock (from gdown)
  Using cached filelock-3.19.1-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: requests[socks] in c:\users\ncc000\appdata\local\programs\python\python313\lib\site-packages (from gdown) (2.32.5)
Requirement already satisfied: tqdm in c:\users\ncc000\appdata\local\programs\python\python313\lib\site-packages (from gdown) (4.67.1)
Collecting soupsieve>1.2 (from beautifulsoup4->gdown)
  Using cached soupsieve-2.8-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4->gdown)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\ncc000\appdata\local\programs\python\python313\lib\site-packages (from requests[socks]->gdown) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ncc000\appdata\local\programs\python\python313\lib\site-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ncc000\appdata\local\programs\python\python313\lib\site-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ncc000\appdata\local\programs\python\python313\lib\site-packages (from requests[socks]->gdown) (2025.8.3)
Collecting PySocks!=1.5.7,>=1.5.6 (from requests[socks]->gdown)
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: colorama in c:\users\ncc000\appdata\roaming\python\python313\site-packages (from tqdm->gdown) (0.4.6)
Using cached gdown-5.2.0-py3-none-any.whl (18 kB)
Downloading beautifulsoup4-4.14.2-py3-none-any.whl (106 kB)
Using cached soupsieve-2.8-py3-none-any.whl (36 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached filelock-3.19.1-py3-none-any.whl (15 kB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Installing collected packages: typing-extensions, soupsieve, PySocks, filelock, beautifulsoup4, gdown

   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ---------------------------------------- 0/6 [typing-extensions]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------ --------------------------------- 1/6 [soupsieve]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   ------------- -------------------------- 2/6 [PySocks]
   -------------------- ------------------- 3/6 [filelock]
   -------------------- ------------------- 3/6 [filelock]
   -------------------- ------------------- 3/6 [filelock]
   -------------------- ------------------- 3/6 [filelock]
   -------------------- ------------------- 3/6 [filelock]
   -------------------- ------------------- 3/6 [filelock]
   -------------------- ------------------- 3/6 [filelock]
   -------------------- ------------------- 3/6 [filelock]
   -------------------- ------------------- 3/6 [filelock]
   -------------------- ------------------- 3/6 [filelock]
   -------------------- ------------------- 3/6 [filelock]
   -------------------- ------------------- 3/6 [filelock]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   -------------------------- ------------- 4/6 [beautifulsoup4]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   --------------------------------- ------ 5/6 [gdown]
   ---------------------------------------- 6/6 [gdown]

Successfully installed PySocks-1.7.1 beautifulsoup4-4.14.2 filelock-3.19.1 gdown-5.2.0 soupsieve-2.8 typing-extensions-4.15.0
Note: you may need to restart the kernel to use updated packages.

In [2]:

file_id = '1yB5qSBOLl96Y563nIewKOU8RN_gsY3dO'  # Make sure it's a string
gdown.download(f'https://drive.google.com/uc?id={file_id}', 'data.csv', quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1yB5qSBOLl96Y563nIewKOU8RN_gsY3dO
To: c:\Users\ncc000\Documents\Algebra_task\New_task\data.csv
100%|██████████| 52.0k/52.0k [00:00<00:00, 40.5MB/s]

'data.csv'

In [58]:
import pandas as pd
import numpy as np
from scipy import stats

In [5]:
# Read the downloaded CSV file
df = pd.read_csv('data.csv')
df.head()

   Unnamed: 0    country food_category  consumption  co2_emission
0           1  Argentina          pork        10.51         37.20
1           2  Argentina       poultry        38.66         41.53
2           3  Argentina          beef        55.48       1712.00
3           4  Argentina     lamb_goat         1.56         54.63
4           5  Argentina          fish         4.36          6.96

In [15]:
df2= df.copy()

In [17]:
df2.tail(30)

      Unnamed: 0     country food_category  consumption  co2_emission
1400        1401   Indonesia     lamb_goat         0.46         16.11
1401        1402   Indonesia          fish        25.65         40.95
1402        1403   Indonesia          eggs         4.88          4.48
1403        1404   Indonesia         dairy        14.82         21.11
1404        1405   Indonesia         wheat        25.45          4.85
1405        1406   Indonesia          rice       134.62        172.27
1406        1407   Indonesia      soybeans         1.12          0.50
1407        1408   Indonesia          nuts         4.92          8.71
1408        1409     Liberia          pork         4.01         14.19
1409        1410     Liberia       poultry         8.91          9.57
1410        1411     Liberia          beef         0.78         24.07
1411        1412     Liberia     lamb_goat         0.48         16.81
1412        1413     Liberia          fish         4.13          6.59
1413        1414     Liberia          eggs         2.05          1.88
1414        1415     Liberia         dairy         3.04          4.33
1415        1416     Liberia         wheat        10.95          2.09
1416        1417     Liberia          rice        94.75        121.25
1417        1418     Liberia      soybeans         0.63          0.28
1418        1419     Liberia          nuts         1.31          2.32
1419        1420  Bangladesh          pork         0.00          0.00
1420        1421  Bangladesh       poultry         1.40          1.50
1421        1422  Bangladesh          beef         1.28         39.50
1422        1423  Bangladesh     lamb_goat         1.33         46.58
1423        1424  Bangladesh          fish        18.07         28.85
1424        1425  Bangladesh          eggs         2.08          1.91
1425        1426  Bangladesh         dairy        21.91         31.21
1426        1427  Bangladesh         wheat        17.47          3.33
1427        1428  Bangladesh          rice       171.73        219.76
1428        1429  Bangladesh      soybeans         0.61          0.27
1429        1430  Bangladesh          nuts         0.72          1.27

In [28]:
# Select Argentina beef consumption
arg_beef = df[(df["country"]=="Argentina") & (df["food_category"]=="beef")]
arg_beef

   Unnamed: 0    country food_category  consumption  co2_emission
2           3  Argentina          beef        55.48        1712.0

In [30]:
arg_consump = arg_beef["consumption"]
arg_consump

2    55.48
Name: consumption, dtype: float64

In [41]:
arg_consump_mean = arg_consump.mean()
arg_consump_mean

np.float64(55.48)

In [43]:
rg_beef_samples = np.random.normal(loc=arg_consump_mean, scale=5, size=30)
rg_beef_samples

array([49.56354949, 57.88806774, 57.77663876, 54.96236431, 45.41655495,
       43.750118  , 51.25182748, 53.88410034, 49.82168765, 53.99514417,
       58.60480154, 58.4355615 , 55.23826446, 59.69279221, 45.01425128,
       60.95381577, 63.08856255, 65.14317958, 49.00011375, 64.59673865,
       53.18090996, 54.1107456 , 49.90924562, 51.04957765, 57.46057125,
       54.86064073, 64.04316227, 55.74699846, 52.81238941, 67.96123007])

In [35]:
# Select Argentina beef consumption
arg_bag = df[(df["country"]=="Bangladesh") & (df["food_category"]=="beef")]
arg_bag.head()

      Unnamed: 0     country food_category  consumption  co2_emission
1421        1422  Bangladesh          beef         1.28          39.5

In [46]:
bag_consum = arg_bag["consumption"]
bag_consum

1421    1.28
Name: consumption, dtype: float64

In [50]:
bag_consum_mean= bag_consum.mean()
bag_consum_mean

np.float64(1.28)

In [51]:
bag_beef_samples = np.random.normal(loc=bag_consum_mean, scale=5, size=30)
bag_beef_samples

array([-8.8236175 ,  5.50051574, 11.75900258,  6.04978039, 11.77223188,
       -4.01397313,  2.92413637, -0.28251323,  5.45072676,  9.78046882,
        0.18844712,  0.24408698, -0.41439241,  4.8400469 ,  2.36996106,
        1.84613277, -2.25573437,  1.17839881,  1.31642497, -2.91344316,
       -0.85202628,  6.30012106,  5.87854366,  8.88943585,  9.53046458,
        0.40616257,  5.83528684, -0.66152227,  2.83706993,  0.3746576 ])

In [59]:
# One-sample t-test
t_stat, p_val = stats.ttest_1samp(bag_beef_samples, 50)

In [60]:
print("T-statistic:", t_stat)

T-statistic: -53.8409337466332

In [63]:
print("P-value:", p_val)

P-value: 1.284815312959485e-30